### ISSUE TITLE
Is the fallthrough intentional?

### ISSUE THREAD

**Issue by SteveRMann** [DrDiettrich/ALib0#2]
This code triggers a fallthrough warning from the compiler.

    switch (check()) {
      case Changing: break; // return false;
      case Changed: state = Stable; //detected!
      case Stable: return pressed == hilo;
    }

Is this intentional?

If yes, then please use [[fallthrough]] to suppress the warning.

    switch (check()) {
      case Changing: break; // return false;
      case Changed: 
         state = Stable; //detected!
         [[fallthrough]];
      case Stable: return pressed == hilo;
    }

**Comment by DrDiettrich** [comment]
Thanks for your comment :-)
The switch also could be be changed into
```
switch (check()) {
case Changing: return false; //undecided
case Changed: state = Stable; break;
//case Stable: break; //NOP
}
return pressed == hilo;
```
What do you think is clearer?

**Comment by DrDiettrich** [comment]
I think that the falllthrough is the right solution, returning false by default.

**Comment by SteveRMann** [comment]
I added `[[fallthrough]];` in my local copy and the button example works just fine, and it compiles with no warnings.

Ironically, I had never heard of [[fallthrough]] before experimenting with Alib0 (how did you come up with that name?).  It was my goal of compiling without warnings that got me researching the warning.

**Comment by DrDiettrich** [comment]
This was my first (and only) attempt to write an **A**rduino **lib**rary version **0**.
After adding the button class I could not find more equally simple and controller independent projects so it's my first and last Arduino library.

Perhaps I was so glad that everything works so that I forgot to check for compiler warnings. Shame on me :-(
